parameters:
#    cms_frontend.example.class: CMS\FrontendBundle\Example

services:
#    cms_frontend.example:
#        class: %cms_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
