fos_facebook:
    alias:  facebook
    app_id: %facebook_app_id%
    secret: %facebook_secret%
    cookie: true
    permissions: [email, user_birthday, user_location]

services:
    my.facebook.user:
        class: CMS\FrontendBundle\Provider\FacebookProvider
        arguments:
            facebook: "@fos_facebook.api"
            userManager: "@fos_user.user_manager"
            validator: "@validator"
