cms_frontend:
    resource: "@CMSFrontendBundle/Resources/config/routing.yml"
    prefix:   /

_security_check:
    pattern:  /login_check
_security_logout:
    pattern:  /logout
fos_facebook_channel:
    resource: "@FOSFacebookBundle/Resources/config/routing.xml"

_facebook_secured:
      pattern: /secured/
      defaults: { _controller: AcmeDemoBundle:Welcome:index }
